#!/bin/bash


#                          I'm a server control script
#
#
#
#                                                                        SIGNALs
#                                     master
# ------------------------------------------------------------------------------
# TERM,INT      Quick shutdown
# QUIT          Graceful shutdown
# HUP           Configuration reload Start the new worker processes with a
#               new configuration Gracefully shutdown the old worker processes
# USR1          Reopen the log files
# USR2          Upgrade Executable on the fly
# WINCH         Gracefully shutdown the worker processes 
# 
#                                     worker
# ------------------------------------------------------------------------------
# TERM,         INT Quick shutdown
# QUIT          Graceful shutdown
# USR1          Reopen the log files 


. conf

GDB_TUI="-tui"
MPID=`cat $PREFIX/$FULLNAME/logs/nginx.pid`

ReopenLog()
{ #{{{

  # wpids=`ps -ef|grep worker|grep $MPID|awk '{print $2}'`

  kill -SIGUSR1 $MPID

} #}}}

InstallConf()
{ #{{{

  cp -Rf $CONF_DIR/* $CONF_TAR/
  cp -f conf.src/* $CONF_TAR/
  cp -Rf conf.src/$PubVer/*.nginx.conf $CONF_TAR/

} #}}}

Kill()
{ #{{{

  kill -SIGQUIT $MPID

} #}}}

Debug()
{ #{{{

  # start debug at 1st worder
  # WPID=`ps -ef | grep $MPID | fgrep -v grep | grep worker | head -n1 | awk '{print $2}'`
  WPID=`pgrep -P $MPID | head -n1`
  gdb $GDB_TUI program $WPID -x gdb.cmd

} #}}}

DebugMain()
{ #{{{

  gdb $GDB_TUI $PREFIX/$FULLNAME/sbin/$FULLNAME -x gdb.start

} #}}}

Strace()
{ #{{{

  while [ 1 ]; do
    WPID=`pgrep -P $MPID | head -n1`
    echo $WPID
    # strace -v -e trace=writev -e write=6 -p $WPID
    strace -v -p $WPID
    echo "-----------------------------------------------------"
  done

} #}}}

StraceDown()
{ #{{{

  SHELLPID=`ps -ef | grep strace | fgrep -v grep | awk '{print $3}'`
  STPID=`ps -ef | grep strace | fgrep -v grep | awk '{print $2}'`
  kill $SHELLPID
  kill $STPID

} #}}}

GenerateConf()
{ #{{{

  CD=$PWD/conf.src/debug

  if [ $DEBUG = 1 ]; then
    echo debug mode
  else
    CD=$PWD/conf.src/release
  fi


  cat \
  conf.src/head.nginx.conf \
  $CD/global.nginx.conf \
  conf.src/http.nginx.conf \
  > $CONF_DIR/nginx.conf

} #}}}

Start()
{ #{{{

  $PREFIX/$FULLNAME/sbin/$FULLNAME

} #}}}


case $1 in 
  rlog|reopenlog)
    ReopenLog
  ;;

  mk|make)
    make
  ;;

  "up")
    make
    echo "------------------------"
    InstallConf
    echo "------------------------"
    Start
  ;;

  "down")
    Kill
  ;;

  "pack")
    echo nothing done
  ;;

  r|restart) 
    make
    Kill
    InstallConf
    Start
  ;;

  "gdb")
    Debug
  ;;

  gm|gdbmain)
    DebugMain
  ;;

  st|strace)
    Strace
  ;;

  "stdown")
    StraceDown
  ;;

  *)
    echo Usage : 
    echo "   " $0 "[mk|make] [up] [down] [r|restart] [gdb] [gm|gdbmain] [st|strace] [stdown]"
  ;;
esac


