# all:
	# gcc -pipe -W -Wall -Wpointer-arith -Wno-unused-parameter -Wno-unused-function -Wunused-variable -Wunused-value -Werror -g3 -I ../nginx-0.6.31/src/core -I ../nginx-0.6.31/src/event -I ../nginx-0.6.31/src/event/modules -I ../ngx_util -I ../nginx-0.6.31/src/os/unix -I ../nginx-0.6.31/objs -o mc_test test_mc.c
# all:
	# gcc -g protocal_engine.c -o pe

all:
	gcc -g ngx_sdb.test.c protocal_engine.c -o s
